### ISSUE TITLE
Node upgrade

### ISSUE THREAD

**Issue by melissawheatley** [matyas-igor/pr-number-action#7]
Hi! Thanks for adding this action. Are you open to upgrading node as 12 has reached end of life? 

![Screen Shot 2022-11-08 at 2 39 48 PM](https://user-images.githubusercontent.com/35042605/200670783-cd68f36a-891b-422f-82c0-effa82fc7a84.png)

**Comment by matyas-igor** [comment]
Hi Melissa! Thanks for your issue, I just did a new release with a node upgrade to the latest supported version
