### ISSUE TITLE
body is undefined at replace

### ISSUE THREAD

**Issue by melissawheatley** [matyas-igor/pr-number-action#9]
Thanks for updating the node version! The change in index.js broke the action, though. 

![Screen Shot 2022-11-09 at 10 08 47 AM](https://user-images.githubusercontent.com/35042605/200920979-8bd76104-0dc8-463b-ab64-929c20e28292.png)

**Comment by matyas-igor** [comment]
Hi Melissa! Thanks again for your feedback, there was an error in the code that I didn't test properly. I pushed a fix, it should work correctly now
